docs: 📝 add section on team calendars
seedcase-project/team pull request #179
Opened 2024-09-13 09:54 UTC by signekb

## Description

These changes are done because I kept forgetting how to do this ☺️ 

Closes #

## Reviewer Focus

This PR needs a quick review. Focus on CHANGES.

## Checklist

- [X] Ran spell-check
- [X] Formatted Markdown
- [X] Rendered website locally

2024-09-16 09:03 UTC, lwjohnst86 requested changes
Nice! Only some small suggestions :relaxed:

2024-09-16 09:03 UTC, lwjohnst86 commented on onboarding/index.qmd
> +need to create an account on teamup.com for this.
```suggestion
need to create an account on Teamup for this.
```

2024-09-16 09:03 UTC, lwjohnst86 commented on onboarding/index.qmd
> +iterations, and so on. For this, we use [Team Up](https://teamup.com/)
```suggestion
iterations, and so on. For this, we use [Teamup](https://teamup.com/)
```

2024-09-16 13:07 UTC, lwjohnst86 approved these changes

2024-09-16 13:07 UTC, merged

2024-09-17 06:36 UTC, K-Beicher reviewed
That looks like it will work on a Mac.