docs: :memo: update guides based on retrospectives
seedcase-project/team pull request #189
Opened 2024-09-25 21:27 UTC by lwjohnst86

## Description

This is a stacked PR. I've done a few updates to the docs based on what we've discussed in the last few retrospectives. I also rearranged and organized the "tasks during iteration" guide.

## Reviewer Focus

This PR needs an in-depth review.

## Checklist

- [x] Ran spell-check
- [x] Formatted Markdown
- [ ] Rendered website locally

2024-09-26 12:45 UTC, K-Beicher approved these changes, later dismissed
Looks sensible to me

2024-09-27 08:38 UTC, martonvago requested changes
Nice!! Just some language comments

2024-09-27 08:38 UTC, martonvago commented on how-we-work/iteration-tasks.qmd
> +In general, we limit meetings as much as is necessary, however some can
```suggestion
In general, we limit meetings as much as possible, however some can
```
At least to me this makes more sense

2024-09-27 08:38 UTC, martonvago commented on how-we-work/iteration-tasks.qmd
> +    request, they will need to do a bit of preparation before hand for
```suggestion
    request, they will need to do a bit of preparation beforehand for
```

2024-09-27 08:38 UTC, martonvago commented on how-we-work/iteration.qmd
> +meeting is in person. The aim of the meeting to discuss and plan the
```suggestion
meeting is in person. The aim of the meeting is to discuss and plan the
```

2024-09-27 08:38 UTC, martonvago commented on how-we-work/iteration.qmd
> +other tasks that are needed, We'll then agree on the number of tasks in
```suggestion
We'll review the current list of tasks on the board and brainstorm any
other tasks that are needed. We'll then agree on the number of tasks in
```

2024-09-30 07:43 UTC, K-Beicher approved these changes, later dismissed
Agree with Marton, looks good!

2024-09-30 09:02 UTC, merged