add three csv files
seedcase-project/team pull request #96
Opened 2024-01-10 14:28 UTC by K-Beicher

2024-01-11 10:49 UTC, lwjohnst86 requested changes
Not sure this is the best repo for this. It will definitely need to easily accessible in the sprout repo.

I made some comments on the data files. Could you also add a README or some file with instructions on what you did to get that data?

2024-01-11 10:49 UTC, lwjohnst86 commented on synthea_data/organizations.csv
This data we don't need. You can delete this.

2024-01-11 10:49 UTC, lwjohnst86 commented on synthea_data/patients.csv
There's a lot of variables in here that we don't need at all. Like name, address, Drivers license, SSN, Passport, race, birthplace, lat, and lon. Basically any really sensitive/specific "personally identifying" information, since Sprout isn't designed around those use cases.

2024-01-11 10:49 UTC, lwjohnst86 commented on synthea_data/conditions.csv
This is fairly ok, but much too big of a dataset. More likely, the ID and Encounter variables are taking up most of the space. Is there any way to use smaller/simpler IDs formats? This looks like UUID or GUIDs are used, which are excessive for our purposes here.

2024-01-11 11:35 UTC, K-Beicher commented on synthea_data/organizations.csv
I brought it over so that we would have a small data set that we can use to work on primary and foreign keys.  I agree that we don't need that type of data, but the rest of the files are too big to bring over.

2024-01-11 11:36 UTC, K-Beicher commented on synthea_data/conditions.csv
Unfortunately no.  The only way to bring it down is to go down in number of participants.  I suspect that if we ran it with only 1000 patients we'd get a more manageable data set.

2024-01-15 08:16 UTC, closed without merging

2024-01-15 08:17 UTC, K-Beicher commented
@lwjohnst86 will you remove the branch associated with this, please?

2024-01-15 08:23 UTC, lwjohnst86 commented
Yes for sure!